version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo `date "+%Y-%m-%d %H:%M:%S"`：开始单元测试
      - mvn clean
  post_build:
    commands:
      - echo `date "+%Y-%m-%d %H:%M:%S"`：开始组建项目
      - mvn package
artifacts:
  files:
<<<<<<< HEAD
    # - .platform/hooks/postdeploy/client_max_body_size.sh
    - .platform/00_myconf.config
    - .platform/nginx/conf.d/proxy.conf
=======
    - Procfile
>>>>>>> dev
    - target/application.jar
  # discard-paths: yes
