version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo `date` 开始单元测试
      - mvn test
  post_build:
    commands:
      - echo `date` 开始组建项目
      - mvn clean package
artifacts:
  files:
    # - .ebextensions/nginx/nginx.conf
    # - .ebextensions/nginx/conf.d/client_max_body_size.conf
    # - .ebextensions/proxy.config
    # - .platform/client_max_body_size.config
    # - .platform/nginx/nginx.conf
    - .platform/nginx/conf.d/client_max_body_size.conf
    - target/application.jar
  # discard-paths: yes
