version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
artifacts:
  files:
    - .platform/hooks/prebuild/environment.sh
    - .platform/hooks/prebuild/tomcat-native.sh
    - .platform/hooks/postdeploy/proxy.sh
    - Procfile
    - target/application.jar
