version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo `date "+%Y-%m-%d %H:%M:%S"`：开始单元测试
      - mvn clean
  post_build:
    commands:
      - echo `date "+%Y-%m-%d %H:%M:%S"`：开始组建项目
      - mvn package
artifacts:
  files:
    - .platform/hooks/prebuild/environment.sh
    - .platform/hooks/prebuild/tomcat-native.sh
    - .platform/hooks/postdeploy/proxy.sh
    - Procfile
    - target/application.jar
