# .bash_profile
# User specific environment and startup programs

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

export PATH=$PATH:$HOME/.local/bin:$HOME/bin

PS1='\e[1;32m\]\u\e[1;30m\]@\e[0;32m\]\h\e[1;30m\]:\e[1;34m\]\w\e[1;37m\]$\e[0m\] '
